apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRRWFLM1pCS01qRU9MWUVFYkJkRGZQREFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRMk5EZGpZbVF4TnkxallqSXdMVFEwTkdZdE9UaGhaUzB3WkRJME56SmtZelV3TTJZdwpJQmNOTWpNeE1qSTRNREV3T1RBeldoZ1BNakExTXpFeU1qQXdNakE1TUROYU1DOHhMVEFyQmdOVkJBTVRKRFkwCk4yTmlaREUzTFdOaU1qQXRORFEwWmkwNU9HRmxMVEJrTWpRM01tUmpOVEF6WmpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUxBbU1JTlcvTTVnc1hvOFRteUphOUdrbzFKTGlyeDAxclJ0UHhpMApvWDd0b3VsZldUOXM2UElsOUlncEdKcVBiVTV5UWFmK2p2R2NWV3cvWHRYT2N2a1pRV0RFY1krUVEybzdZT3pvCmxFdmFmbmlwSU9RNG8xT1Z2ZmQrSEo3VXVuK2RvZ3hseVkyeDFld3pVWjRPNTVueHRLQmc1ZmE3aWQ5dm9WMlgKa2p3amlVcWtLbWt2OFBNK3BVTS8yc0RGYVh4ZjVqWUM2V2w0S2JyaVVRZ1BsMitLbDYvL3RwSW5UL0FGMXlaWAovNFV6V3lYN205TmJKMzFvWmx1T0kvdThnUWRKUm5YVjNoL2pWdGtxK1VIeXp3WkptSDFrSFR0b0RTVFNTcHhKCmo5eEJ6aGs1dVZmQ3B0Q0RHWVFRREtMQW9TOTRUd0kxVUFxUVFFSS9Iak1HVmZNQmlRaHhOWXR3NU5vZXhUVE0KaU9DcG5mQWJ1UXZDOXdpVFY4S0o0R0xNUjc4RWhrVHpPQkhaNUVEQkxXY2FxbUszREExNk1TWEV4TTZBb1BnKwp5U3VicHdkaUNsSHhZUjZ0ZGFacTBEOHVHWUIzeTNlSWFUWnpDK2Rwc1hmREcwWmRzdW9RNHVKTmFWbVhQdm1oCk1NZzB5MlZYbmVZS3N4dG5ZWDVpTEFNVlZRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVU1cE1lc2w5S2ZiK0ZVQU5zbTNENmsrdVo2TjB3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFDd2lpUDFrTWZ2d2xsOEdSaE11QW5wSDBpbGwzTGNZSURZaDNnTDM4dDJVCmVhZEJsVmgyQ29QcVJSc25xZUpwQW9HYTkxakM1WDU2THhYS1NtZW54T0xXdDJ6NjEvRkpvdGVmejByQm91MFQKNFFNZ28wVXJta1lmSWo3Wm9TS3N1Mi8yZXZONVJIYk1pcnNrQ1hqbEJHMnNRRjBMMTlaa0d6ZE9QMzUyU2xBbApsRzZJSlVNei9sNzR6V0F4cS9sb3FEclp6QnZ1OUVlVVdYTksrTVpjVjR6Tm9wTmJHRFZuejZiYWJnMUE0ZGN1CmZNRkpzU2IrVVA5RGhyL3Y1QTRyWHdhWW9UL1hLNit4RjlqdHc4TTkwWC9WcW1xWVlwd3ZhYjJyZ0plQjVjZS8KUDZUakJraWZxODZQMXhybkZQTE9DRVFURmlxTXJQejk4U0dzYWJzcy92a3pVQ25TV0J2cm5ZNElSQklBRm96TwpEcXg2RnJ1SjhHTFVyQ2t0TGxEU3N0R0ptemJlK1dULzRBMVZyQkZ4VjkvMTJLRHZXYm1adVg3NytGREFZS3E5CjByMkp0aS8wRXoxME1rbHJCc2FROSt2eUJuK2VaYlphclNzUE43TC9xS1JNTzVRVElJNm1aeWNGQncxNkQ5bUwKVGxrcUpYYnhPdVpHOFJjSURSbDFmUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.138.199.58
  name: gke_extreme-signal-409318_us-east1-b_my-gke-cluster
- cluster:
    server: https://35.190.129.5
  name: my-gke-cluster
contexts:
- context:
    cluster: gke_extreme-signal-409318_us-east1-b_my-gke-cluster
    user: gke_extreme-signal-409318_us-east1-b_my-gke-cluster
  name: gke_extreme-signal-409318_us-east1-b_my-gke-cluster
- context:
    cluster: my-gke-cluster
    user: my-gke-cluster
  name: my-gke-context
current-context: gke_extreme-signal-409318_us-east1-b_my-gke-cluster
kind: Config
preferences: {}
users:
- name: gke_extreme-signal-409318_us-east1-b_my-gke-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      provideClusterInfo: true
