apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops-python
  template:
    metadata:
      labels:
        app: demo-devops-python
    spec:
      containers:
      - name: demo-devops-python
        image: devsu/test-example-01:python-app-1.0
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: demo-devops-python-configmap
              key: DJANGO_SECRET_KEY
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: demo-devops-python-configmap
              key: DATABASE_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-devops-python-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: demo-devops-python-service
spec:
  selector:
    app: demo-devops-python
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
 --- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-devops-python-configmap
data:
  DJANGO_SECRET_KEY: "django-insecure-wc2i2*6^17$9!u+(u66@q_rg)++n1x-^(0-$3yz2f(n=_-o*7="
  DATABASE_NAME: "db.sqlite3"
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-devops-python-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXdjMmkyKjZeMTckOSF1Kyh1NjZAcV9yZykrK24xeC1eKDAtJDN5ejJmKG49Xy1vKjc9
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-python-ingress
spec:
  rules:
  - host: your-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-devops-python-service
            port:
              number: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-devops-python-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-devops-python-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
